package view.gui.utilResources;

/**
 * Contains all the code names for the necessary files.
 * @author Tasos Papadopoulos
 * @author Thodwris Myridhs
 * @version 13.1.2021
 */
public enum Image {
    APP_ICON,INTRO_PAGE_LOGO,INTRO_PAGE_BACKGROUND_IMG,OPTIONS_PAGE_BACKGROUND_IMG,
    ENGLISH_FLAG,GREEK_FLAG,SCORES_PAGE_BACKGROUND_IMG,PLAY_PAGE_BACKGROUND_IMG,
    ONE_PLAYER_PAGE_BACKGROUND_IMG,LOADING_SCREEN_PAGE_IMG,TWO_PLAYERS_GAMEMODE_BACKGROUND_IMG,
    W_KEY_IMG,A_KEY_IMG,S_KEY_IMG,D_KEY_IMG,UP_KEY_IMG,LEFT_KEY_IMG,DOWN_KEY_IMG,RIGHT_KEY_IMG,
    QUESTION_IMG_TEST_IMG,FINISH_PAGE_BACKGROUND_IMG,ONE_PLAYER_SELECTION_PAGE_BACKGROUND_IMG,
    ONE_PLAYER_BETTING_PAGE_BACKGROUND_IMG,ERROR_FRAME_BACKGROUND_IMG;
}
